### ISSUE TITLE
Not able to get Click Event of DropdownWarning

### ISSUE THREAD

**Issue by indiascope** [Brudigem/DropDownWarning#1]
Sir,

you can help me i am not able to get click event of dropdown warning.
DropdwonWarning extends LinearLayout. so i write down code for normal LinearLayout click event but i am not able to get click event.

this is my code 

           dropDownWarning = new DropDownWarning.Builder(ShoutziApplication.getInstance(),
                (ViewGroup) ShoutziApplication.getInstance().getCurrentActivity().findViewById(android.R.id.content)).message(messageText).
            
                backgroundColor(ContextCompat.getColor(ShoutziApplication.getInstance(),R.color.black_transparent_color)).
                foregroundColor(ContextCompat.getColor(ShoutziApplication.getInstance(),R.color.white)).
                interpolatorIn(new BounceInterpolator()).
                interpolatorOut(new AnticipateOvershootInterpolator()).
                build();

        dropDownWarning.show();

        dropDownWarning.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                UIUtil.toast(mContext,"Click on Drop down View");
                Intent intent = handleRedirectionFlowOnNotificationClick(mContext, notificationDetail);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_CLEAR_TASK |      Intent.FLAG_ACTIVITY_NEW_TASK);
                mContext.startActivity(intent);
                mContext.finish();

            }
        });

**Comment by Norbert515** [comment]
Hey,
it was because the text view is on top of it. I updatet the library and added the method "setOnClickListener".
Just download the new .aar and your code should work.

**Comment by indiascope** [comment]
Thanks for help. finally click event working.
